name: flutterlibdata
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.1.2
  firebase_core: ^3.1.0
  flutter_bloc: ^8.1.6
  intl: ^0.17.0
  firebase_auth: ^5.1.0
  equatable: ^2.0.5
  cloud_firestore: ^5.0.1
  firebase_storage: ^12.0.1
  http: ^1.2.1
  flutter_dotenv: ^5.1.0
  camera: ^0.11.0+1
  image_picker: ^1.1.2
  cached_network_image: ^3.2.0
  flutter_barcode_scanner: ^2.0.0
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/.env
    - assets/img/open-book.png