// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDw_qpfic0vZFvu5dqOU2RgGa7YYFPeaDc',
    appId: '1:488703376294:web:5e941f6c2aa91a09f76d67',
    messagingSenderId: '488703376294',
    projectId: 'flutterlibdata',
    authDomain: 'flutterlibdata.firebaseapp.com',
    storageBucket: 'flutterlibdata.appspot.com',
    measurementId: 'G-2QT1X25B2C',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCwnyJClKHLCtsYaXZRMIEJRNRLIROSbN4',
    appId: '1:488703376294:android:fb0658056694d7aaf76d67',
    messagingSenderId: '488703376294',
    projectId: 'flutterlibdata',
    storageBucket: 'flutterlibdata.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBkVIbw4TXeEhVV0fS92J6v5OgHeJFOy-I',
    appId: '1:488703376294:ios:a9ec9869608dfc84f76d67',
    messagingSenderId: '488703376294',
    projectId: 'flutterlibdata',
    storageBucket: 'flutterlibdata.appspot.com',
    iosBundleId: 'com.example.flutterlibdata',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBkVIbw4TXeEhVV0fS92J6v5OgHeJFOy-I',
    appId: '1:488703376294:ios:a9ec9869608dfc84f76d67',
    messagingSenderId: '488703376294',
    projectId: 'flutterlibdata',
    storageBucket: 'flutterlibdata.appspot.com',
    iosBundleId: 'com.example.flutterlibdata',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDw_qpfic0vZFvu5dqOU2RgGa7YYFPeaDc',
    appId: '1:488703376294:web:ef00592f91703c1ff76d67',
    messagingSenderId: '488703376294',
    projectId: 'flutterlibdata',
    authDomain: 'flutterlibdata.firebaseapp.com',
    storageBucket: 'flutterlibdata.appspot.com',
    measurementId: 'G-D55LY8N0CY',
  );
}
